CREATE TABLE IF NOT EXISTS imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename VARCHAR(255) NOT NULL,
    checksum CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'processing',
    imported_count INTEGER NOT NULL DEFAULT 0,
    rejected_count INTEGER NOT NULL DEFAULT 0,
    duplicate_count INTEGER NOT NULL DEFAULT 0,
    skipped_count INTEGER NOT NULL DEFAULT 0,
    duration_ms INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,
    CONSTRAINT imports_checksum_unique UNIQUE (checksum),
    CONSTRAINT imports_status_check CHECK (status IN ('processing', 'completed', 'failed'))
);

CREATE TABLE IF NOT EXISTS transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL REFERENCES imports(id),
    transaction_id VARCHAR(64) NOT NULL,
    occurred_at TIMESTAMP NOT NULL,
    terminal_id VARCHAR(64) NOT NULL,
    card_number VARCHAR(64) NOT NULL,
    account VARCHAR(64) NOT NULL,
    amount_cents BIGINT NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    merchant_id VARCHAR(64) NOT NULL,
    merchant_name VARCHAR(160) NOT NULL,
    currency CHAR(3) NOT NULL,
    external_reference TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT transactions_transaction_id_unique UNIQUE (transaction_id),
    CONSTRAINT transactions_amount_check CHECK (amount_cents > 0),
    CONSTRAINT transactions_type_check CHECK (
        transaction_type IN ('debit', 'credit', 'reversal', 'adjustment')
    ),
    CONSTRAINT transactions_status_check CHECK (
        status IN ('approved', 'declined', 'reversed', 'pending')
    )
);

CREATE INDEX IF NOT EXISTS transactions_occurred_at_idx ON transactions (occurred_at);
CREATE INDEX IF NOT EXISTS transactions_merchant_idx ON transactions (merchant_name);
CREATE INDEX IF NOT EXISTS transactions_currency_status_idx ON transactions (currency, status);
CREATE INDEX IF NOT EXISTS transactions_type_idx ON transactions (transaction_type);

CREATE TABLE IF NOT EXISTS rejected_rows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    import_id BIGINT NOT NULL REFERENCES imports(id) ON DELETE CASCADE,
    row_number INTEGER NOT NULL,
    original_row JSONB NOT NULL,
    validation_errors JSONB NOT NULL,
    rejection_reason VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS rejected_rows_import_idx
    ON rejected_rows (import_id, row_number);
